[2019-08-23 17:25:10 -0400] [7683] [INFO] Starting gunicorn 19.7.1
[2019-08-23 17:25:10 -0400] [7683] [INFO] Listening at: http://0.0.0.0:8000 (7683)
[2019-08-23 17:25:10 -0400] [7683] [INFO] Using worker: sync
[2019-08-23 17:25:10 -0400] [7686] [INFO] Booting worker with pid: 7686
[2019-08-23 17:25:10 -0400] [7686] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/nicklecompte/Source/seqr-direct/seqrenv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/Users/nicklecompte/Source/seqr-direct/seqrenv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/Users/nicklecompte/Source/seqr-direct/seqrenv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/nicklecompte/Source/seqr-direct/seqrenv/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/nicklecompte/Source/seqr-direct/seqrenv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/Users/nicklecompte/Source/seqr-direct/seqrenv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/nicklecompte/Source/seqr-direct/seqrenv/lib/python3.7/site-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)
ModuleNotFoundError: No module named 'wsgi'
[2019-08-23 17:25:10 -0400] [7686] [INFO] Worker exiting (pid: 7686)
[2019-08-23 17:25:10 -0400] [7683] [INFO] Shutting down: Master
[2019-08-23 17:25:10 -0400] [7683] [INFO] Reason: Worker failed to boot.
